feat(lockdown): restore confidentiality
Signed-off-by: Sebastien Varrette <sebastien.varrette@ssi.gouv.fr>

diff --git a/convert-grub-config b/convert-grub-config
--- a/convert-grub-config
+++ b/convert-grub-config
@@ -34,10 +34,13 @@ COLOR_RESET="\033[0m"
 GRUB_D="grub.d"
 
 ################################################################################
-info()    { echo -e "${COLOR_BOLD}[+] $*${COLOR_RESET}"; }
-error()   { echo -e "${COLOR_BOLD}*** ERROR *** $*${COLOR_RESET}"; }
+info() { echo -e "${COLOR_BOLD}[+] $*${COLOR_RESET}"; }
+error() { echo -e "${COLOR_BOLD}*** ERROR *** $*${COLOR_RESET}"; }
 warning() { echo -e "/!\ WARNING: $*"; }
-print_error_and_exit() { error "$*"; exit 1; }
+print_error_and_exit() {
+  error "$*"
+  exit 1
+}
 usage() {
   cat <<EOF
 $(basename "$0"): convert/sanitize grub configs listed under ${GRUB_D}/<N>_*.cfg
@@ -76,11 +79,20 @@ convert() {
 # Check for options
 while [ $# -ge 1 ]; do
   case $1 in
-    -h | --help) usage; exit 0;;
-    -i | --input) shift; INFILE="$1";;
-    -n | --dry-run) CMD_PREFIX="echo" ;;
-    -x | --exec)    CMD_PREFIX= ;;
-    *) OPTS="$*"; break;;
+  -h | --help)
+    usage
+    exit 0
+    ;;
+  -i | --input)
+    shift
+    INFILE="$1"
+    ;;
+  -n | --dry-run) CMD_PREFIX="echo" ;;
+  -x | --exec) CMD_PREFIX= ;;
+  *)
+    OPTS="$*"
+    break
+    ;;
   esac
   shift
 done
@@ -89,22 +101,24 @@ done
 info "setup (if needed) ${GRUB_D}"
 $CMD_PREFIX mkdir -p "${GRUB_D}"
 
-
 # Safeguards
 [ ! -d "${GRUB_D}" ] && print_error_and_exit "Unexisting directory for grub configuration '${GRUB_D}'"
 if [ -n "${INFILE}" ]; then
   [ ! -f "${INFILE}" ] && print_error_and_exit "Unexisting file '${INFILE}'"
 fi
 
-
 for f in $(ls "${GRUB_D}/" | grep -E '^[0-9]+.*\.cfg'); do
   info "convert ${GRUB_D}/${f} => ${f}"
   filename="${f}"
-  [ -n "${CMD_PREFIX}" ] && filename="/dev/null"
-  $CMD_PREFIX cat "${GRUB_D}/${f}" | \
-    sed "s/GRUB_CMDLINE_LINUX=\"\$GRUB_CMDLINE_LINUX \(.*\)\"/\1/g" | \
-    sed "s/GRUB_CMDLINE_LINUX_DEFAULT=\"\$GRUB_CMDLINE_LINUX_DEFAULT \(.*\)\"/\1/g" | \
-    grep -v -E 'kpkg|kver' | \
+  if [ -n "${CMD_PREFIX}" ]; then
+    filename="/dev/null"
+    echo "cat ${GRUB_D}/${f} \| sed 's/GRUB_CMDLINE_LINUX=[...]/g' | sed [...] | grep -v -E 'kpkg|kver'"
+    continue
+  fi
+  $CMD_PREFIX cat "${GRUB_D}/${f}" |
+    sed "s/GRUB_CMDLINE_LINUX=\"\$GRUB_CMDLINE_LINUX \(.*\)\"/\1/g" |
+    sed "s/GRUB_CMDLINE_LINUX_DEFAULT=\"\$GRUB_CMDLINE_LINUX_DEFAULT \(.*\)\"/\1/g" |
+    grep -v -E 'kpkg|kver' |
     tee "${filename}"
   # Kept for archiving: initial way of collecting the cmdline
   # ( . "${GRUB_D}/${f}" && \
